server:
  port: 9093
spring:
  application:
    name: inventory-failover
  zipkin:
    base-url: http://192.168.99.101:9411
eureka:
  client:
    service-url:
      defaultZone: http://netflix:eureka@localhost:8761/eureka